<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contents = [
            [
                'categoryId' => 10,
                'hostId' => 2,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/qY1C2Bp5P1Y',
                'title' => 'Glow Up',
                'bigDescription' => 'كلووأب برنامج سريع غادي تعلم فيه مع كريمة باج أخصائية الأناقة و الجمال كيفاش تعتاني بنفسك كسيدة و تهتمي بالمظهر و الجمال ديالك',
                'smallDescription' => 'كلووأب برنامج سريع غادي تعلم فيه مع كريمة باج أخصائية الأناقة و الجمال كيفاش تعتاني بنفسك كسيدة و تهتمي بالمظهر و الجمال ديالك',
                'contentType' => 'podcast',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => '01:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 11,
                'hostId' => 6,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/qY1C2Bp5P1Y',
                'title' => 'مدخل إلى التسويق الرقمي',
                'bigDescription' => null,
                'smallDescription' => 'كلشي اليوم كيتكلم على التسويق الرقمي و التجارة الالكترونية. واش هو موضة أم نوع جديد ديال التسويق لي يقدر يغير الطريقة باش كتشتاغل و يساعدك تزيد من المداخيل و الأرباح ديالك بشكل كبير؟ شاهد الفيديو باش تعرف..',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 11,
                'hostId' => 6,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/qY1C2Bp5P1Y',
                'title' => 'مدخل إلى التسويق الرقمي',
                'bigDescription' => null,
                'smallDescription' => 'كلشي اليوم كيتكلم على التسويق الرقمي و التجارة الالكترونية. واش هو موضة أم نوع جديد ديال التسويق لي يقدر يغير الطريقة باش كتشتاغل و يساعدك تزيد من المداخيل و الأرباح ديالك بشكل كبير؟ شاهد الفيديو باش تعرف..',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 13,
                'hostId' => 7,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'مدرسة الحياة',
                'bigDescription' => 'انا افكر إذا أنا موجود، قريناها ولا سمعناها واكيد تجاوزناها بدون تحليل .كل نهار كتعيش أحداث جديدة كتخليك تزيدها على ماقبل وتفكر في التفاصيل ديالها من بعد .
                علاقات،عمل،أسرة ضروري كتحس بالزحام في راسك وانت كتقراها في دماغك صوت وصورة....وكينتج على هادشي بزاف ديال الأفكار الأخرى اللي كتلقاها في بودكاست مدرسة الحياة ..
                اجي نفكرو مجموعين ونعرف التفاصيل بصوت ادق.',
                'smallDescription' => 'كل شيء يعبر عنك، كلماتك، ابتساماتك، حركاتك.. اعرف نفسك و واجه ما تخفيه حتى تزيد من جودة حياتك',
                'contentType' => 'podcast',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 13,
                'hostId' => 5,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'تطوير القدرات العقلية والذاكرة',
                'bigDescription' => null,
                'smallDescription' => 'تطوير القدرات العقلية والذاكرة',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 7,
                'hostId' => 5,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'مهارات بناء العلاقات الاجتماعية',
                'bigDescription' => null,
                'smallDescription' => 'التواصل و بناء العلاقات هو سر النجاح الاجتماعي الذي يساهم في النجاح العام للفرد داخل المجتمع وتحقيق اهدافه على المستوى الشخصي والمهني.',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 13,
                'hostId' => 8,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'فن الاستماع الفعال و التعامل مع النقد',
                'bigDescription' => null,
                'smallDescription' => 'أهمية الاستماع الفعال لا يمكن التغاضي عليها، فهــي المفتــاحح لفهم أعمق لوجهـات النظـر المختلفـة. في هـذه الـدورة السريعة ستكتشف مهـارات الاسـتماع الفعـال واسـراتيجيات التعامـل مـع الانتقادات.',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 11,
                'hostId' => 9,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'بناء العلامة الذاتية',
                'bigDescription' => null,
                'smallDescription' => 'بناء العلامة الذاتية',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 14,
                'hostId' => 10,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'مقدمة في فن التفاوض التجاري',
                'bigDescription' => null,
                'smallDescription' => 'التفاوض هو اساس رحلتك التجارية فلابد من التحضر لها بشكل جيد و اعتماد أساليب و استراتيجيات ستساعدك بشكل كبير لتحقيق أهدافك التجارية',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 13,
                'hostId' => 5,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'الذكاء العاطفي',
                'bigDescription' => null,
                'smallDescription' => 'الذكاء العاطفي اصبح من الكفاأت اللازمة لكل شخص ان ينميها لانها عنصر مغذي للعلاقات المهنية و الشخصية',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 13,
                'hostId' => 5,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'الثقة بالنفس',
                'bigDescription' => null,
                'smallDescription' => 'عدم الشعور بالفرح و الاستمتاع بالانجازات و التردد في اتخاذ القرارات كيدلو على انعدام القة بالنفس لكن ممكن انها تتعالج باتباع الخطوات المناسبة و هذا ما ستتعلم في هذه الدورة',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 1,
                'hostId' => 4,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'التدبير المالي و إدارة الميزانية الشخصية',
                'bigDescription' => null,
                'smallDescription' => 'التدبير المالي و إدارة الميزانية الشخصية',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoryId' => 4,
                'hostId' => 5,
                'programId' => null,
                'image' => 'image_url_1',
                'imageFlex' => 'image_flex_url_1',
                'video' => 'https://www.youtube.com/embed/C3ufCI6bbtg',
                'title' => 'إدارة التوتر و الضغوط اليومية',
                'bigDescription' => null,
                'smallDescription' => 'إدارة التوتر و الضغوط اليومية',
                'contentType' => 'formation',
                'isActive' => true,
                'isComing' => false,
                'isCertify' => false,
                'pricing' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'document' => 'document_url_1',
                'condition' => 'Conditions for Content 1',
                'duration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more content data as needed
        ];

        // Insert data into the contents table
        foreach ($contents as $content) {
            Content::create($content);
        }
    }
}
