<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'karima',
                'lastName' => 'BAJ',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'شغوفة بعالم الجمال والموضة منذ صغرها، حصلت كريمة باج على دبلوم في  الأزياء والتصميم عام 2013 بالدار البيضاء. تشتغل منذ عام 2023 كمصممة ديكور وفنانة مكياج لدى أكاديمية النهراوند',
                'faceboock' => 'https://www.facebook.com/karima.koukita.3',
                'linkdin' => 'https://www.linkedin.com/in/karima-baj-4a88ba307/',
                'instagram' => 'https://www.instagram.com/baj.karima/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'karimabaj09@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Niama ',
                'lastName' => 'MESMOUKI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'مديرة مشروع نهرواند أكاديمي، استشارية بمجال الرقمنة و الأعمال، مؤلفة و مدربة معتمدة للمهارات التجارية. حاصلة على إجارة في العلوم الاقتصادية ثم ماجستر في ريادة الأعمال من كلية الاقتصاد بالدار البيضاء و على ماجستر في علوم التسيير من جامعة كيبيك.',
                'faceboock' => 'https://www.facebook.com/mesmoukiniama/',
                'linkdin' => 'https://www.linkedin.com/in/niama-mesmouki/',
                'instagram' => 'https://www.instagram.com/niamamesmouki/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'niama.mesmouki@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Youssef ',
                'lastName' => 'GUERRAOUI FILALI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'يوسف كراوي فيلالي خبير في مجال الحكامة المالية، باحث في الاقتصاد و رئيس المركز المغربي للحكامة و التسيير',
                'faceboock' => 'https://www.facebook.com/youssef.guerraouifilali/',
                'linkdin' => 'https://www.linkedin.com/in/youssef-guerraoui-filali-4a853b40/',
                'instagram' => 'https://www.instagram.com/youssefguerraoui/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'youssefelhoulaili@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Maria',
                'lastName' => 'BAGGATI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'ماريا بغاطي مدربة معتمدة و خبيرة في مجال التدريب وتطوير المهارات الشخصية والبرمجة اللغوية العصبية. حاصلة على عدة شهادات دولية تدربت بشكل مباشر من قبل الدكتور ريتشارد باندلر مخترع البرمجة اللغوية العصبية، وقد ساعدت مئات المهنيين في تحقيق أهدافهم المهنية من خلال نهج مبتكر وشخصي.',
                'faceboock' => 'https://www.facebook.com/maria.baggati',
                'linkdin' => 'https://www.linkedin.com/maria.baggati',
                'instagram' => 'https://www.instagram.com/mariabaggati/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'mariabaggati@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Hakim ',
                'lastName' => 'AMRI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'حكيم عمري استشاري و مدرب تسويق رقمي حاصل على ديبلوم الماجستر بالتسيير من جامعة عبد المالك السعدي بطنجة و على عدة شهادات بمجال التسويق.',
                'faceboock' => 'https://www.facebook.com/hakim.amri.96?locale=fr_FR',
                'linkdin' => 'https://www.linkedin.com/in/hakim-amri-550069b2?originalSubdomain=ma',
                'instagram' => 'https://www.instagram.com/hakim.amri.officiel/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'hakimamri@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Houda',
                'lastName' => 'ARBAIN',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'هدى أربعين خريجة جامعة العلوم الإنسانية مسلك علم الاجتماع بالمحمدية و حاصلة على ديبلومات في علوم التجارة و التسيير، اشغلت في مجال اللوجيستيك و التسيير التجاري قبل الالتحاق بأكاديمية نهرواند كمسؤولة عن جودة المحتوى ثم كمسؤولة عن المحتوى.',
                'faceboock' => 'https://www.facebook.com/nahrawandacademyofficial',
                'linkdin' => 'https://www.linkedin.com/in/houda-arbain-3a37b42b5/',
                'instagram' => 'https://www.instagram.com/houda.arbain/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'houda87arbain@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Hanane ',
                'lastName' => 'BENHADDI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'حنان بنهدي صانعة محتوى على الانستغرام لأكثر من مئة ألف متابع مهتمين بمواضيع تطوير الذات وريادة الأعمال. ألقت أكثر من 30 محاضرة في الجامعات المغربية حيث شاركت قصص نجاحها لتحفيز الطلاب و أطرت عدة ورش عمل للتنمية الذاتية و دورات تدريبية حول "المهارات الشخصية".',
                'faceboock' => 'https://www.facebook.com/hananebenha',
                'linkdin' => 'https://www.linkedin.com/in/hanane-benhaddi-326020197/',
                'instagram' => 'https://www.instagram.com/hananebenhaddi/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'benhaddihanane@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Niama  ',
                'lastName' => 'MESMOUKI',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'مديرة مشروع نهرواند أكاديمي، استشارية بمجال الرقمنة و الأعمال، مؤلفة و مدربة معتمدة للمهارات التجارية. حاصلة على إجارة في العلوم الاقتصادية ثم ماجستر في ريادة الأعمال من كلية الاقتصاد بالدار البيضاء و على ماجستر في علوم التسيير من جامعة كيبيك',
                'faceboock' => 'https://www.facebook.com/mesmoukiniama/',
                'linkdin' => 'https://www.linkedin.com/in/niama-mesmouki/',
                'instagram' => 'https://www.instagram.com/niamamesmouki/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'mesmoukiniama@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => '664dcaced12c7_maroc.png',
                'cover' => '664dcaced12c7_maroc.png',
                'firstName' => 'Rabii',
                'lastName' => 'OUTAMHA',
                'isLogin' => false,
                'isPopular' => true,
                'password_change' => false,
                'isUpdated' => false,
                'isDelete' => false,
                'biographie' => 'ربيع أوتمهى، أستاذ و باحث و استشاري في مجال التسويق الاستراتيجي، حاصل على دكتوراه في التسيير بجامعة الحسن الثاني بالدار البيضاء.',
                'faceboock' => 'https://www.facebook.com/outamharabii',
                'linkdin' => 'https://www.linkedin.com/in/rabiioutamha/',
                'instagram' => 'https://www.instagram.com/rabiioutamha/',
                'datebirt' => null,
                'status_matrimonial' => null,
                'numChild' => null,
                'profission' => null,
                'email' => 'rabii.outamha@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
